package by.http.news.controller;

public enum CommandName {
	
	REGISTRATION, AUTHORIZATION, USER_ACTION, USER_ANSWER, INDEX, USER_AUTHORIZATION, USER_REGISTRATION, MAIN, 
	LOGGEDOUT, UNKNOWN_COMMAND

}
